#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Booky")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DAL.Properties.Settings.Default.BookyConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LOGIN_USUARIO")]
		public int SP_LOGIN_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(150)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PasswordHash", DbType="VarChar(255)")] string passwordHash, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] ref System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RolNombre", DbType="VarChar(50)")] ref string rolNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, passwordHash, idUsuario, rolNombre, sUCCESS, eRRORID);
			idUsuario = ((System.Nullable<int>)(result.GetParameterValue(2)));
			rolNombre = ((string)(result.GetParameterValue(3)));
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GENERAR_CODIGO_RECUPERACION")]
		public int SP_GENERAR_CODIGO_RECUPERACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorreoElectronico", DbType="NVarChar(255)")] string correoElectronico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoRecuperacion", DbType="VarChar(10)")] ref string codigoRecuperacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correoElectronico, codigoRecuperacion, sUCCESS, eRRORID);
			codigoRecuperacion = ((string)(result.GetParameterValue(1)));
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VERIFICAR_EMAIL_CON_CODIGO")]
		public int SP_VERIFICAR_EMAIL_CON_CODIGO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="VarChar(10)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo, sUCCESS, eRRORID);
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GENERAR_CODIGO_VERIFICACION")]
		public int SP_GENERAR_CODIGO_VERIFICACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(150)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="VarChar(10)")] ref string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, codigo, sUCCESS, eRRORID);
			codigo = ((string)(result.GetParameterValue(1)));
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_REGISTRAR_USUARIO")]
		public int SP_REGISTRAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(20)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(150)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PasswordHash", DbType="VarChar(255)")] string passwordHash, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(20)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreRol", DbType="VarChar(50)")] string nombreRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] ref System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula, nombre, email, passwordHash, telefono, nombreRol, idUsuario, sUCCESS, eRRORID);
			idUsuario = ((System.Nullable<int>)(result.GetParameterValue(6)));
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(7)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CAMBIAR_CONTRASENA_CON_CODIGO")]
		public int SP_CAMBIAR_CONTRASENA_CON_CODIGO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoRecuperacion", DbType="VarChar(10)")] string codigoRecuperacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevaContrasenaHash", DbType="NVarChar(255)")] string nuevaContrasenaHash, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ConfirmacionContrasenaHash", DbType="NVarChar(255)")] string confirmacionContrasenaHash, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoRecuperacion, nuevaContrasenaHash, confirmacionContrasenaHash, sUCCESS, eRRORID);
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AGREGAR_USUARIO")]
		public int SP_AGREGAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreRol", DbType="VarChar(50)")] string nombreRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(20)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(150)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PasswordHash", DbType="VarChar(255)")] string passwordHash, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(20)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreRol, cedula, nombre, email, passwordHash, telefono, sUCCESS, eRRORID);
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(6)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EDITAR_INFORMACION_MI_PERFIL")]
		public int SP_EDITAR_INFORMACION_MI_PERFIL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(20)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, nombre, telefono, sUCCESS, eRRORID);
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTIVAR_DESACTIVAR_SERVICIO")]
		public int SP_ACTIVAR_DESACTIVAR_SERVICIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdServicio", DbType="Int")] System.Nullable<int> idServicio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoFinal", DbType="Bit")] ref System.Nullable<bool> estadoFinal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idServicio, idUsuario, estadoFinal, sUCCESS, eRRORID);
			estadoFinal = ((System.Nullable<bool>)(result.GetParameterValue(2)));
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_SERVICIO")]
		public int SP_ACTUALIZAR_SERVICIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdServicio", DbType="Int")] System.Nullable<int> idServicio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(500)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DuracionMinutos", DbType="Int")] System.Nullable<int> duracionMinutos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Precio", DbType="Decimal(10,2)")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermiteDescuento", DbType="Bit")] System.Nullable<bool> permiteDescuento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PorcentajeDescuento", DbType="Decimal(5,2)")] System.Nullable<decimal> porcentajeDescuento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="Bit")] System.Nullable<bool> estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, idServicio, nombre, descripcion, duracionMinutos, precio, permiteDescuento, porcentajeDescuento, estado, sUCCESS, eRRORID);
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(9)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CREAR_SERVICIO")]
		public int SP_CREAR_SERVICIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(500)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DuracionMinutos", DbType="Int")] System.Nullable<int> duracionMinutos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Precio", DbType="Decimal(10,2)")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermiteDescuento", DbType="Bit")] System.Nullable<bool> permiteDescuento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PorcentajeDescuento", DbType="Decimal(5,2)")] System.Nullable<decimal> porcentajeDescuento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdServicioCreado", DbType="Int")] ref System.Nullable<int> idServicioCreado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, nombre, descripcion, duracionMinutos, precio, permiteDescuento, porcentajeDescuento, idServicioCreado, sUCCESS, eRRORID);
			idServicioCreado = ((System.Nullable<int>)(result.GetParameterValue(7)));
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(8)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SOLICITAR_CITA_PROFESIONAL")]
		public int SP_SOLICITAR_CITA_PROFESIONAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdServicio", DbType="Int")] System.Nullable<int> idServicio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaCita", DbType="DateTime")] System.Nullable<System.DateTime> fechaCita, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MensajeSolicitud", DbType="NVarChar(MAX)")] string mensajeSolicitud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCita", DbType="Int")] ref System.Nullable<int> idCita, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, idServicio, fechaCita, mensajeSolicitud, idCita, sUCCESS, eRRORID);
			idCita = ((System.Nullable<int>)(result.GetParameterValue(4)));
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(5)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_SERVICIOS_DISPONIBLES")]
		public ISingleResult<SP_LISTAR_SERVICIOS_DISPONIBLESResult> SP_LISTAR_SERVICIOS_DISPONIBLES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreServicio", DbType="NVarChar(100)")] string nombreServicio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreProfesional", DbType="NVarChar(100)")] string nombreProfesional, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Profesion", DbType="NVarChar(100)")] string profesion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreServicio, nombreProfesional, profesion, sUCCESS, eRRORID);
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((ISingleResult<SP_LISTAR_SERVICIOS_DISPONIBLESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_INFORMACION_MI_PERFIL")]
		public ISingleResult<SP_OBTENER_INFORMACION_MI_PERFILResult> SP_OBTENER_INFORMACION_MI_PERFIL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, sUCCESS, eRRORID);
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_OBTENER_INFORMACION_MI_PERFILResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_REGISTRAR_PAGO_ONVO")]
		public int SP_REGISTRAR_PAGO_ONVO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReferenceId", DbType="NVarChar(100)")] string referenceId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Decimal(18,2)")] System.Nullable<decimal> amount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Currency", DbType="NVarChar(10)")] string currency, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(255)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, referenceId, amount, currency, description, sUCCESS, eRRORID);
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(5)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_USUARIO_POR_ID")]
		public ISingleResult<SP_OBTENER_USUARIO_POR_IDResult> SP_OBTENER_USUARIO_POR_ID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, sUCCESS, eRRORID);
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_OBTENER_USUARIO_POR_IDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_SERVICIOS_PROFESIONAL")]
		public ISingleResult<SP_LISTAR_SERVICIOS_PROFESIONALResult> SP_LISTAR_SERVICIOS_PROFESIONAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreServicio", DbType="NVarChar(100)")] string nombreServicio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, nombreServicio, sUCCESS, eRRORID);
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_LISTAR_SERVICIOS_PROFESIONALResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_CITAS_CLIENTE")]
		public ISingleResult<SP_LISTAR_CITAS_CLIENTEResult> SP_LISTAR_CITAS_CLIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, sUCCESS, eRRORID);
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_LISTAR_CITAS_CLIENTEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_CITAS_PROFESIONAL")]
		public ISingleResult<SP_LISTAR_CITAS_PROFESIONALResult> SP_LISTAR_CITAS_PROFESIONAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, sUCCESS, eRRORID);
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_LISTAR_CITAS_PROFESIONALResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_REPROGRAMAR_CITA_PROFESIONAL")]
		public int SP_REPROGRAMAR_CITA_PROFESIONAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCita", DbType="Int")] System.Nullable<int> idCita, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevaFechaCita", DbType="DateTime")] System.Nullable<System.DateTime> nuevaFechaCita, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, idCita, nuevaFechaCita, sUCCESS, eRRORID);
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_ESTADO_CITA")]
		public int SP_ACTUALIZAR_ESTADO_CITA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCita", DbType="Int")] System.Nullable<int> idCita, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Aprobada", DbType="Bit")] System.Nullable<bool> aprobada, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MotivoRechazo", DbType="NVarChar(500)")] string motivoRechazo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCita, aprobada, motivoRechazo, sUCCESS, eRRORID);
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACTUALIZAR_PERFIL_PROFESIONAL")]
		public int SP_ACTUALIZAR_PERFIL_PROFESIONAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Profesion", DbType="NVarChar(100)")] string profesion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(500)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="NVarChar(200)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Latitud", DbType="Decimal(10,8)")] System.Nullable<decimal> latitud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Longitud", DbType="Decimal(11,8)")] System.Nullable<decimal> longitud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="Bit")] System.Nullable<bool> estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUCCESS", DbType="Bit")] ref System.Nullable<bool> sUCCESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, profesion, descripcion, direccion, latitud, longitud, estado, sUCCESS, eRRORID);
			sUCCESS = ((System.Nullable<bool>)(result.GetParameterValue(7)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_REGISTRAR_CLIENTE_ONVO")]
		public int SP_REGISTRAR_CLIENTE_ONVO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OnvoCustomerId", DbType="VarChar(100)")] string onvoCustomerId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(255)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(255)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(50)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resultado", DbType="Bit")] ref System.Nullable<bool> resultado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorID", DbType="Int")] ref System.Nullable<int> errorID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, onvoCustomerId, email, nombre, telefono, resultado, errorID);
			resultado = ((System.Nullable<bool>)(result.GetParameterValue(5)));
			errorID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PAYMENT_LINKS_USUARIO")]
		public ISingleResult<SP_OBTENER_PAYMENT_LINKS_USUARIOResult> SP_OBTENER_PAYMENT_LINKS_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(50)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, status);
			return ((ISingleResult<SP_OBTENER_PAYMENT_LINKS_USUARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PAYMENT_LINK_POR_ID")]
		public ISingleResult<SP_OBTENER_PAYMENT_LINK_POR_IDResult> SP_OBTENER_PAYMENT_LINK_POR_ID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OnvoPaymentLinkId", DbType="VarChar(100)")] string onvoPaymentLinkId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), onvoPaymentLinkId);
			return ((ISingleResult<SP_OBTENER_PAYMENT_LINK_POR_IDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_METODOS_PAGO_CLIENTE")]
		public ISingleResult<SP_OBTENER_METODOS_PAGO_CLIENTEResult> SP_OBTENER_METODOS_PAGO_CLIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OnvoCustomerId", DbType="VarChar(100)")] string onvoCustomerId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), onvoCustomerId);
			return ((ISingleResult<SP_OBTENER_METODOS_PAGO_CLIENTEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_REGISTRAR_METODO_PAGO_ONVO")]
		public int SP_REGISTRAR_METODO_PAGO_ONVO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OnvoCustomerId", DbType="VarChar(100)")] string onvoCustomerId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OnvoPaymentMethodId", DbType="VarChar(100)")] string onvoPaymentMethodId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Last4", DbType="VarChar(4)")] string last4, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Brand", DbType="VarChar(50)")] string brand, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpMonth", DbType="VarChar(2)")] string expMonth, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpYear", DbType="VarChar(4)")] string expYear, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resultado", DbType="Bit")] ref System.Nullable<bool> resultado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorID", DbType="Int")] ref System.Nullable<int> errorID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, onvoCustomerId, onvoPaymentMethodId, last4, brand, expMonth, expYear, resultado, errorID);
			resultado = ((System.Nullable<bool>)(result.GetParameterValue(7)));
			errorID = ((System.Nullable<int>)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_REGISTRAR_PAYMENT_LINK_ONVO")]
		public int SP_REGISTRAR_PAYMENT_LINK_ONVO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OnvoCustomerId", DbType="VarChar(100)")] string onvoCustomerId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OnvoPaymentLinkId", DbType="VarChar(100)")] string onvoPaymentLinkId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReferenceId", DbType="VarChar(100)")] string referenceId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentUrl", DbType="VarChar(500)")] string paymentUrl, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Decimal(18,2)")] System.Nullable<decimal> amount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Currency", DbType="VarChar(10)")] string currency, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(500)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpiresAt", DbType="DateTime")] System.Nullable<System.DateTime> expiresAt, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resultado", DbType="Bit")] ref System.Nullable<bool> resultado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorID", DbType="Int")] ref System.Nullable<int> errorID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, onvoCustomerId, onvoPaymentLinkId, referenceId, paymentUrl, amount, currency, description, expiresAt, resultado, errorID);
			resultado = ((System.Nullable<bool>)(result.GetParameterValue(9)));
			errorID = ((System.Nullable<int>)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class SP_LISTAR_SERVICIOS_DISPONIBLESResult
	{
		
		private int _IdServicio;
		
		private string _NombreServicio;
		
		private string _Descripcion;
		
		private System.Nullable<int> _DuracionMinutos;
		
		private decimal _Precio;
		
		private bool _PermiteDescuento;
		
		private System.Nullable<decimal> _PorcentajeDescuento;
		
		private System.DateTime _FechaCreacion;
		
		private bool _Estado;
		
		private int _IdPerfil;
		
		private string _NombreProfesional;
		
		private string _Profesion;
		
		public SP_LISTAR_SERVICIOS_DISPONIBLESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdServicio", DbType="Int NOT NULL")]
		public int IdServicio
		{
			get
			{
				return this._IdServicio;
			}
			set
			{
				if ((this._IdServicio != value))
				{
					this._IdServicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreServicio", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreServicio
		{
			get
			{
				return this._NombreServicio;
			}
			set
			{
				if ((this._NombreServicio != value))
				{
					this._NombreServicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuracionMinutos", DbType="Int")]
		public System.Nullable<int> DuracionMinutos
		{
			get
			{
				return this._DuracionMinutos;
			}
			set
			{
				if ((this._DuracionMinutos != value))
				{
					this._DuracionMinutos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(10,2) NOT NULL")]
		public decimal Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermiteDescuento", DbType="Bit NOT NULL")]
		public bool PermiteDescuento
		{
			get
			{
				return this._PermiteDescuento;
			}
			set
			{
				if ((this._PermiteDescuento != value))
				{
					this._PermiteDescuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorcentajeDescuento", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PorcentajeDescuento
		{
			get
			{
				return this._PorcentajeDescuento;
			}
			set
			{
				if ((this._PorcentajeDescuento != value))
				{
					this._PorcentajeDescuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this._FechaCreacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPerfil", DbType="Int NOT NULL")]
		public int IdPerfil
		{
			get
			{
				return this._IdPerfil;
			}
			set
			{
				if ((this._IdPerfil != value))
				{
					this._IdPerfil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProfesional", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreProfesional
		{
			get
			{
				return this._NombreProfesional;
			}
			set
			{
				if ((this._NombreProfesional != value))
				{
					this._NombreProfesional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Profesion
		{
			get
			{
				return this._Profesion;
			}
			set
			{
				if ((this._Profesion != value))
				{
					this._Profesion = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_INFORMACION_MI_PERFILResult
	{
		
		private string _Nombre;
		
		private string _Email;
		
		private string _Cedula;
		
		private string _Telefono;
		
		private string _Profesion;
		
		private string _Descripcion;
		
		private string _Direccion;
		
		private System.Nullable<decimal> _CalificacionPromedio;
		
		private System.Nullable<int> _TotalCalificaciones;
		
		public SP_OBTENER_INFORMACION_MI_PERFILResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesion", DbType="VarChar(100)")]
		public string Profesion
		{
			get
			{
				return this._Profesion;
			}
			set
			{
				if ((this._Profesion != value))
				{
					this._Profesion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(255)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalificacionPromedio", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> CalificacionPromedio
		{
			get
			{
				return this._CalificacionPromedio;
			}
			set
			{
				if ((this._CalificacionPromedio != value))
				{
					this._CalificacionPromedio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalCalificaciones", DbType="Int")]
		public System.Nullable<int> TotalCalificaciones
		{
			get
			{
				return this._TotalCalificaciones;
			}
			set
			{
				if ((this._TotalCalificaciones != value))
				{
					this._TotalCalificaciones = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_USUARIO_POR_IDResult
	{
		
		private int _IdUsuario;
		
		private string _Nombre;
		
		private string _Email;
		
		private string _Cedula;
		
		private int _IdRol;
		
		private string _Telefono;
		
		private System.DateTime _FechaRegistro;
		
		private bool _Estado;
		
		public SP_OBTENER_USUARIO_POR_IDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", DbType="Int NOT NULL")]
		public int IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					this._IdRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this._FechaRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class SP_LISTAR_SERVICIOS_PROFESIONALResult
	{
		
		private int _IdServicio;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private System.Nullable<int> _DuracionMinutos;
		
		private decimal _Precio;
		
		private bool _PermiteDescuento;
		
		private System.Nullable<decimal> _PorcentajeDescuento;
		
		private System.DateTime _FechaCreacion;
		
		private bool _Estado;
		
		public SP_LISTAR_SERVICIOS_PROFESIONALResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdServicio", DbType="Int NOT NULL")]
		public int IdServicio
		{
			get
			{
				return this._IdServicio;
			}
			set
			{
				if ((this._IdServicio != value))
				{
					this._IdServicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuracionMinutos", DbType="Int")]
		public System.Nullable<int> DuracionMinutos
		{
			get
			{
				return this._DuracionMinutos;
			}
			set
			{
				if ((this._DuracionMinutos != value))
				{
					this._DuracionMinutos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(10,2) NOT NULL")]
		public decimal Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermiteDescuento", DbType="Bit NOT NULL")]
		public bool PermiteDescuento
		{
			get
			{
				return this._PermiteDescuento;
			}
			set
			{
				if ((this._PermiteDescuento != value))
				{
					this._PermiteDescuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorcentajeDescuento", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PorcentajeDescuento
		{
			get
			{
				return this._PorcentajeDescuento;
			}
			set
			{
				if ((this._PorcentajeDescuento != value))
				{
					this._PorcentajeDescuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this._FechaCreacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class SP_LISTAR_CITAS_CLIENTEResult
	{
		
		private int _IdCita;
		
		private System.DateTime _FechaCita;
		
		private System.Nullable<int> _DuracionMinutos;
		
		private decimal _PrecioAcordado;
		
		private string _Estado;
		
		private string _MensajeSolicitud;
		
		private string _MotivoRechazo;
		
		private string _MotivoCancelacion;
		
		private System.DateTime _FechaSolicitud;
		
		private System.Nullable<System.DateTime> _FechaRespuesta;
		
		private string _CedulaUsuario;
		
		private string _NombreUsuario;
		
		private string _EmailUsuario;
		
		private string _TelefonoUsuario;
		
		private string _NombreProfesional;
		
		private string _Profesion;
		
		private string _DescripcionPerfil;
		
		private string _Direccion;
		
		private string _EmailProfesional;
		
		private string _TelefonoProfesional;
		
		private string _NombreServicio;
		
		public SP_LISTAR_CITAS_CLIENTEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCita", DbType="Int NOT NULL")]
		public int IdCita
		{
			get
			{
				return this._IdCita;
			}
			set
			{
				if ((this._IdCita != value))
				{
					this._IdCita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCita", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCita
		{
			get
			{
				return this._FechaCita;
			}
			set
			{
				if ((this._FechaCita != value))
				{
					this._FechaCita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuracionMinutos", DbType="Int")]
		public System.Nullable<int> DuracionMinutos
		{
			get
			{
				return this._DuracionMinutos;
			}
			set
			{
				if ((this._DuracionMinutos != value))
				{
					this._DuracionMinutos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioAcordado", DbType="Decimal(10,2) NOT NULL")]
		public decimal PrecioAcordado
		{
			get
			{
				return this._PrecioAcordado;
			}
			set
			{
				if ((this._PrecioAcordado != value))
				{
					this._PrecioAcordado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MensajeSolicitud", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string MensajeSolicitud
		{
			get
			{
				return this._MensajeSolicitud;
			}
			set
			{
				if ((this._MensajeSolicitud != value))
				{
					this._MensajeSolicitud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotivoRechazo", DbType="VarChar(255)")]
		public string MotivoRechazo
		{
			get
			{
				return this._MotivoRechazo;
			}
			set
			{
				if ((this._MotivoRechazo != value))
				{
					this._MotivoRechazo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotivoCancelacion", DbType="VarChar(255)")]
		public string MotivoCancelacion
		{
			get
			{
				return this._MotivoCancelacion;
			}
			set
			{
				if ((this._MotivoCancelacion != value))
				{
					this._MotivoCancelacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSolicitud", DbType="DateTime NOT NULL")]
		public System.DateTime FechaSolicitud
		{
			get
			{
				return this._FechaSolicitud;
			}
			set
			{
				if ((this._FechaSolicitud != value))
				{
					this._FechaSolicitud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRespuesta", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaRespuesta
		{
			get
			{
				return this._FechaRespuesta;
			}
			set
			{
				if ((this._FechaRespuesta != value))
				{
					this._FechaRespuesta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CedulaUsuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CedulaUsuario
		{
			get
			{
				return this._CedulaUsuario;
			}
			set
			{
				if ((this._CedulaUsuario != value))
				{
					this._CedulaUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this._NombreUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailUsuario", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string EmailUsuario
		{
			get
			{
				return this._EmailUsuario;
			}
			set
			{
				if ((this._EmailUsuario != value))
				{
					this._EmailUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoUsuario", DbType="VarChar(20)")]
		public string TelefonoUsuario
		{
			get
			{
				return this._TelefonoUsuario;
			}
			set
			{
				if ((this._TelefonoUsuario != value))
				{
					this._TelefonoUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProfesional", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreProfesional
		{
			get
			{
				return this._NombreProfesional;
			}
			set
			{
				if ((this._NombreProfesional != value))
				{
					this._NombreProfesional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Profesion
		{
			get
			{
				return this._Profesion;
			}
			set
			{
				if ((this._Profesion != value))
				{
					this._Profesion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionPerfil", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string DescripcionPerfil
		{
			get
			{
				return this._DescripcionPerfil;
			}
			set
			{
				if ((this._DescripcionPerfil != value))
				{
					this._DescripcionPerfil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(255)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailProfesional", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string EmailProfesional
		{
			get
			{
				return this._EmailProfesional;
			}
			set
			{
				if ((this._EmailProfesional != value))
				{
					this._EmailProfesional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoProfesional", DbType="VarChar(20)")]
		public string TelefonoProfesional
		{
			get
			{
				return this._TelefonoProfesional;
			}
			set
			{
				if ((this._TelefonoProfesional != value))
				{
					this._TelefonoProfesional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreServicio", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreServicio
		{
			get
			{
				return this._NombreServicio;
			}
			set
			{
				if ((this._NombreServicio != value))
				{
					this._NombreServicio = value;
				}
			}
		}
	}
	
	public partial class SP_LISTAR_CITAS_PROFESIONALResult
	{
		
		private int _IdCita;
		
		private System.DateTime _FechaCita;
		
		private System.Nullable<int> _DuracionMinutos;
		
		private decimal _PrecioAcordado;
		
		private string _Estado;
		
		private string _MensajeSolicitud;
		
		private string _MotivoRechazo;
		
		private string _MotivoCancelacion;
		
		private System.DateTime _FechaSolicitud;
		
		private System.Nullable<System.DateTime> _FechaRespuesta;
		
		private string _CedulaUsuario;
		
		private string _NombreUsuario;
		
		private string _EmailUsuario;
		
		private string _TelefonoUsuario;
		
		private string _NombreProfesional;
		
		private string _Profesion;
		
		private string _DescripcionPerfil;
		
		private string _Direccion;
		
		private string _EmailProfesional;
		
		private string _TelefonoProfesional;
		
		private string _NombreServicio;
		
		public SP_LISTAR_CITAS_PROFESIONALResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCita", DbType="Int NOT NULL")]
		public int IdCita
		{
			get
			{
				return this._IdCita;
			}
			set
			{
				if ((this._IdCita != value))
				{
					this._IdCita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCita", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCita
		{
			get
			{
				return this._FechaCita;
			}
			set
			{
				if ((this._FechaCita != value))
				{
					this._FechaCita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuracionMinutos", DbType="Int")]
		public System.Nullable<int> DuracionMinutos
		{
			get
			{
				return this._DuracionMinutos;
			}
			set
			{
				if ((this._DuracionMinutos != value))
				{
					this._DuracionMinutos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioAcordado", DbType="Decimal(10,2) NOT NULL")]
		public decimal PrecioAcordado
		{
			get
			{
				return this._PrecioAcordado;
			}
			set
			{
				if ((this._PrecioAcordado != value))
				{
					this._PrecioAcordado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MensajeSolicitud", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string MensajeSolicitud
		{
			get
			{
				return this._MensajeSolicitud;
			}
			set
			{
				if ((this._MensajeSolicitud != value))
				{
					this._MensajeSolicitud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotivoRechazo", DbType="VarChar(255)")]
		public string MotivoRechazo
		{
			get
			{
				return this._MotivoRechazo;
			}
			set
			{
				if ((this._MotivoRechazo != value))
				{
					this._MotivoRechazo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotivoCancelacion", DbType="VarChar(255)")]
		public string MotivoCancelacion
		{
			get
			{
				return this._MotivoCancelacion;
			}
			set
			{
				if ((this._MotivoCancelacion != value))
				{
					this._MotivoCancelacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSolicitud", DbType="DateTime NOT NULL")]
		public System.DateTime FechaSolicitud
		{
			get
			{
				return this._FechaSolicitud;
			}
			set
			{
				if ((this._FechaSolicitud != value))
				{
					this._FechaSolicitud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRespuesta", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaRespuesta
		{
			get
			{
				return this._FechaRespuesta;
			}
			set
			{
				if ((this._FechaRespuesta != value))
				{
					this._FechaRespuesta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CedulaUsuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CedulaUsuario
		{
			get
			{
				return this._CedulaUsuario;
			}
			set
			{
				if ((this._CedulaUsuario != value))
				{
					this._CedulaUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this._NombreUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailUsuario", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string EmailUsuario
		{
			get
			{
				return this._EmailUsuario;
			}
			set
			{
				if ((this._EmailUsuario != value))
				{
					this._EmailUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoUsuario", DbType="VarChar(20)")]
		public string TelefonoUsuario
		{
			get
			{
				return this._TelefonoUsuario;
			}
			set
			{
				if ((this._TelefonoUsuario != value))
				{
					this._TelefonoUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProfesional", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreProfesional
		{
			get
			{
				return this._NombreProfesional;
			}
			set
			{
				if ((this._NombreProfesional != value))
				{
					this._NombreProfesional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Profesion
		{
			get
			{
				return this._Profesion;
			}
			set
			{
				if ((this._Profesion != value))
				{
					this._Profesion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionPerfil", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string DescripcionPerfil
		{
			get
			{
				return this._DescripcionPerfil;
			}
			set
			{
				if ((this._DescripcionPerfil != value))
				{
					this._DescripcionPerfil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(255)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailProfesional", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string EmailProfesional
		{
			get
			{
				return this._EmailProfesional;
			}
			set
			{
				if ((this._EmailProfesional != value))
				{
					this._EmailProfesional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoProfesional", DbType="VarChar(20)")]
		public string TelefonoProfesional
		{
			get
			{
				return this._TelefonoProfesional;
			}
			set
			{
				if ((this._TelefonoProfesional != value))
				{
					this._TelefonoProfesional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreServicio", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreServicio
		{
			get
			{
				return this._NombreServicio;
			}
			set
			{
				if ((this._NombreServicio != value))
				{
					this._NombreServicio = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PAYMENT_LINKS_USUARIOResult
	{
		
		private int _Id;
		
		private int _IdUsuario;
		
		private string _OnvoCustomerId;
		
		private string _OnvoPaymentLinkId;
		
		private string _ReferenceId;
		
		private string _PaymentUrl;
		
		private decimal _Amount;
		
		private string _Currency;
		
		private string _Description;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _ExpiresAt;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
		private System.Nullable<System.DateTime> _FechaActualizacion;
		
		public SP_OBTENER_PAYMENT_LINKS_USUARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnvoCustomerId", DbType="VarChar(100)")]
		public string OnvoCustomerId
		{
			get
			{
				return this._OnvoCustomerId;
			}
			set
			{
				if ((this._OnvoCustomerId != value))
				{
					this._OnvoCustomerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnvoPaymentLinkId", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string OnvoPaymentLinkId
		{
			get
			{
				return this._OnvoPaymentLinkId;
			}
			set
			{
				if ((this._OnvoPaymentLinkId != value))
				{
					this._OnvoPaymentLinkId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceId", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ReferenceId
		{
			get
			{
				return this._ReferenceId;
			}
			set
			{
				if ((this._ReferenceId != value))
				{
					this._ReferenceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentUrl", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string PaymentUrl
		{
			get
			{
				return this._PaymentUrl;
			}
			set
			{
				if ((this._PaymentUrl != value))
				{
					this._PaymentUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2) NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				if ((this._Currency != value))
				{
					this._Currency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiresAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpiresAt
		{
			get
			{
				return this._ExpiresAt;
			}
			set
			{
				if ((this._ExpiresAt != value))
				{
					this._ExpiresAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this._FechaCreacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualizacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaActualizacion
		{
			get
			{
				return this._FechaActualizacion;
			}
			set
			{
				if ((this._FechaActualizacion != value))
				{
					this._FechaActualizacion = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PAYMENT_LINK_POR_IDResult
	{
		
		private int _Id;
		
		private int _IdUsuario;
		
		private string _OnvoCustomerId;
		
		private string _OnvoPaymentLinkId;
		
		private string _ReferenceId;
		
		private string _PaymentUrl;
		
		private decimal _Amount;
		
		private string _Currency;
		
		private string _Description;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _ExpiresAt;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
		private System.Nullable<System.DateTime> _FechaActualizacion;
		
		public SP_OBTENER_PAYMENT_LINK_POR_IDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnvoCustomerId", DbType="VarChar(100)")]
		public string OnvoCustomerId
		{
			get
			{
				return this._OnvoCustomerId;
			}
			set
			{
				if ((this._OnvoCustomerId != value))
				{
					this._OnvoCustomerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnvoPaymentLinkId", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string OnvoPaymentLinkId
		{
			get
			{
				return this._OnvoPaymentLinkId;
			}
			set
			{
				if ((this._OnvoPaymentLinkId != value))
				{
					this._OnvoPaymentLinkId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceId", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ReferenceId
		{
			get
			{
				return this._ReferenceId;
			}
			set
			{
				if ((this._ReferenceId != value))
				{
					this._ReferenceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentUrl", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string PaymentUrl
		{
			get
			{
				return this._PaymentUrl;
			}
			set
			{
				if ((this._PaymentUrl != value))
				{
					this._PaymentUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2) NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				if ((this._Currency != value))
				{
					this._Currency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiresAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpiresAt
		{
			get
			{
				return this._ExpiresAt;
			}
			set
			{
				if ((this._ExpiresAt != value))
				{
					this._ExpiresAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this._FechaCreacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualizacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaActualizacion
		{
			get
			{
				return this._FechaActualizacion;
			}
			set
			{
				if ((this._FechaActualizacion != value))
				{
					this._FechaActualizacion = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_METODOS_PAGO_CLIENTEResult
	{
		
		private int _Id;
		
		private int _IdUsuario;
		
		private string _OnvoCustomerId;
		
		private string _OnvoPaymentMethodId;
		
		private string _Last4;
		
		private string _Brand;
		
		private string _ExpMonth;
		
		private string _ExpYear;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
		private System.Nullable<bool> _Activo;
		
		public SP_OBTENER_METODOS_PAGO_CLIENTEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnvoCustomerId", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string OnvoCustomerId
		{
			get
			{
				return this._OnvoCustomerId;
			}
			set
			{
				if ((this._OnvoCustomerId != value))
				{
					this._OnvoCustomerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnvoPaymentMethodId", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string OnvoPaymentMethodId
		{
			get
			{
				return this._OnvoPaymentMethodId;
			}
			set
			{
				if ((this._OnvoPaymentMethodId != value))
				{
					this._OnvoPaymentMethodId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last4", DbType="VarChar(4)")]
		public string Last4
		{
			get
			{
				return this._Last4;
			}
			set
			{
				if ((this._Last4 != value))
				{
					this._Last4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand", DbType="VarChar(50)")]
		public string Brand
		{
			get
			{
				return this._Brand;
			}
			set
			{
				if ((this._Brand != value))
				{
					this._Brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpMonth", DbType="VarChar(2)")]
		public string ExpMonth
		{
			get
			{
				return this._ExpMonth;
			}
			set
			{
				if ((this._ExpMonth != value))
				{
					this._ExpMonth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpYear", DbType="VarChar(4)")]
		public string ExpYear
		{
			get
			{
				return this._ExpYear;
			}
			set
			{
				if ((this._ExpYear != value))
				{
					this._ExpYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this._FechaCreacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit")]
		public System.Nullable<bool> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this._Activo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
