<?xml version="1.0" encoding="utf-8"?><Database Name="Booky" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ASUSMEY;Initial Catalog=Booky;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="BookyConnectionString3" Provider="System.Data.SqlClient" />
  <Function Name="dbo.SP_LOGIN_USUARIO" Method="SP_LOGIN_USUARIO">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="PasswordHash" Parameter="passwordHash" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="RolNombre" Parameter="rolNombre" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_GENERAR_CODIGO_RECUPERACION" Method="SP_GENERAR_CODIGO_RECUPERACION">
    <Parameter Name="CorreoElectronico" Parameter="correoElectronico" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CodigoRecuperacion" Parameter="codigoRecuperacion" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_VERIFICAR_EMAIL_CON_CODIGO" Method="SP_VERIFICAR_EMAIL_CON_CODIGO">
    <Parameter Name="Codigo" Parameter="codigo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_GENERAR_CODIGO_VERIFICACION" Method="SP_GENERAR_CODIGO_VERIFICACION">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="Codigo" Parameter="codigo" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_REGISTRAR_USUARIO" Method="SP_REGISTRAR_USUARIO">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="PasswordHash" Parameter="passwordHash" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="NombreRol" Parameter="nombreRol" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CAMBIAR_CONTRASENA_CON_CODIGO" Method="SP_CAMBIAR_CONTRASENA_CON_CODIGO">
    <Parameter Name="CodigoRecuperacion" Parameter="codigoRecuperacion" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="NuevaContrasenaHash" Parameter="nuevaContrasenaHash" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ConfirmacionContrasenaHash" Parameter="confirmacionContrasenaHash" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_AGREGAR_USUARIO" Method="SP_AGREGAR_USUARIO">
    <Parameter Name="NombreRol" Parameter="nombreRol" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="PasswordHash" Parameter="passwordHash" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EDITAR_INFORMACION_MI_PERFIL" Method="SP_EDITAR_INFORMACION_MI_PERFIL">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ACTIVAR_DESACTIVAR_SERVICIO" Method="SP_ACTIVAR_DESACTIVAR_SERVICIO">
    <Parameter Name="IdServicio" Parameter="idServicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="EstadoFinal" Parameter="estadoFinal" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ACTUALIZAR_SERVICIO" Method="SP_ACTUALIZAR_SERVICIO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdServicio" Parameter="idServicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="DuracionMinutos" Parameter="duracionMinutos" Type="System.Int32" DbType="Int" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="PermiteDescuento" Parameter="permiteDescuento" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PorcentajeDescuento" Parameter="porcentajeDescuento" Type="System.Decimal" DbType="Decimal(5,2)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CREAR_SERVICIO" Method="SP_CREAR_SERVICIO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="DuracionMinutos" Parameter="duracionMinutos" Type="System.Int32" DbType="Int" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="PermiteDescuento" Parameter="permiteDescuento" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PorcentajeDescuento" Parameter="porcentajeDescuento" Type="System.Decimal" DbType="Decimal(5,2)" />
    <Parameter Name="IdServicioCreado" Parameter="idServicioCreado" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SOLICITAR_CITA_PROFESIONAL" Method="SP_SOLICITAR_CITA_PROFESIONAL">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdServicio" Parameter="idServicio" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaCita" Parameter="fechaCita" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="MensajeSolicitud" Parameter="mensajeSolicitud" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="IdCita" Parameter="idCita" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_LISTAR_SERVICIOS_DISPONIBLES" Method="SP_LISTAR_SERVICIOS_DISPONIBLES">
    <Parameter Name="NombreServicio" Parameter="nombreServicio" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="NombreProfesional" Parameter="nombreProfesional" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Profesion" Parameter="profesion" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="SP_LISTAR_SERVICIOS_DISPONIBLESResult">
      <Column Name="IdServicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreServicio" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DuracionMinutos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="PermiteDescuento" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PorcentajeDescuento" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IdPerfil" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreProfesional" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Profesion" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OBTENER_INFORMACION_MI_PERFIL" Method="SP_OBTENER_INFORMACION_MI_PERFIL">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="SP_OBTENER_INFORMACION_MI_PERFILResult">
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Cedula" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Profesion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CalificacionPromedio" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="TotalCalificaciones" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_REGISTRAR_PAGO_ONVO" Method="SP_REGISTRAR_PAGO_ONVO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ReferenceId" Parameter="referenceId" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Amount" Parameter="amount" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Currency" Parameter="currency" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_OBTENER_USUARIO_POR_ID" Method="SP_OBTENER_USUARIO_POR_ID">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="SP_OBTENER_USUARIO_POR_IDResult">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Cedula" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IdRol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_REPROGRAMAR_CITA_PROFESIONAL" Method="SP_REPROGRAMAR_CITA_PROFESIONAL">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdCita" Parameter="idCita" Type="System.Int32" DbType="Int" />
    <Parameter Name="NuevaFechaCita" Parameter="nuevaFechaCita" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CANCELAR_CITA_CLIENTE" Method="SP_CANCELAR_CITA_CLIENTE">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdCita" Parameter="idCita" Type="System.Int32" DbType="Int" />
    <Parameter Name="MotivoCancelacion" Parameter="motivoCancelacion" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ACTUALIZAR_ESTADO_CITA" Method="SP_ACTUALIZAR_ESTADO_CITA">
    <Parameter Name="IdCita" Parameter="idCita" Type="System.Int32" DbType="Int" />
    <Parameter Name="Aprobada" Parameter="aprobada" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="MotivoRechazo" Parameter="motivoRechazo" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ACTUALIZAR_PERFIL_PROFESIONAL" Method="SP_ACTUALIZAR_PERFIL_PROFESIONAL">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Profesion" Parameter="profesion" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Latitud" Parameter="latitud" Type="System.Decimal" DbType="Decimal(10,8)" />
    <Parameter Name="Longitud" Parameter="longitud" Type="System.Decimal" DbType="Decimal(11,8)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_REGISTRAR_CLIENTE_ONVO" Method="SP_REGISTRAR_CLIENTE_ONVO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="OnvoCustomerId" Parameter="onvoCustomerId" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Resultado" Parameter="resultado" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ErrorID" Parameter="errorID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_OBTENER_PAYMENT_LINKS_USUARIO" Method="SP_OBTENER_PAYMENT_LINKS_USUARIO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SP_OBTENER_PAYMENT_LINKS_USUARIOResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OnvoCustomerId" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OnvoPaymentLinkId" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ReferenceId" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentUrl" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ExpiresAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaActualizacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OBTENER_PAYMENT_LINK_POR_ID" Method="SP_OBTENER_PAYMENT_LINK_POR_ID">
    <Parameter Name="OnvoPaymentLinkId" Parameter="onvoPaymentLinkId" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_OBTENER_PAYMENT_LINK_POR_IDResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OnvoCustomerId" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OnvoPaymentLinkId" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ReferenceId" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentUrl" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ExpiresAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaActualizacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OBTENER_METODOS_PAGO_CLIENTE" Method="SP_OBTENER_METODOS_PAGO_CLIENTE">
    <Parameter Name="OnvoCustomerId" Parameter="onvoCustomerId" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_OBTENER_METODOS_PAGO_CLIENTEResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OnvoCustomerId" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="OnvoPaymentMethodId" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Last4" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ExpMonth" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="ExpYear" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_REGISTRAR_METODO_PAGO_ONVO" Method="SP_REGISTRAR_METODO_PAGO_ONVO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="OnvoCustomerId" Parameter="onvoCustomerId" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="OnvoPaymentMethodId" Parameter="onvoPaymentMethodId" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Last4" Parameter="last4" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Brand" Parameter="brand" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ExpMonth" Parameter="expMonth" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="ExpYear" Parameter="expYear" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="Resultado" Parameter="resultado" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ErrorID" Parameter="errorID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_REGISTRAR_PAYMENT_LINK_ONVO" Method="SP_REGISTRAR_PAYMENT_LINK_ONVO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="OnvoCustomerId" Parameter="onvoCustomerId" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="OnvoPaymentLinkId" Parameter="onvoPaymentLinkId" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ReferenceId" Parameter="referenceId" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="PaymentUrl" Parameter="paymentUrl" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Amount" Parameter="amount" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Currency" Parameter="currency" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="ExpiresAt" Parameter="expiresAt" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Resultado" Parameter="resultado" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ErrorID" Parameter="errorID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_OBTENER_RESUMEN_PAGOS_CLIENTE" Method="SP_OBTENER_RESUMEN_PAGOS_CLIENTE">
    <Parameter Name="OnvoCustomerId" Parameter="onvoCustomerId" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_OBTENER_RESUMEN_PAGOS_CLIENTEResult">
      <Column Name="TotalPagos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PagosCompletados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PagosPendientes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PagosCancelados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PagosExpirados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPagado" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="TotalPendiente" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OBTENER_PAYMENT_LINKS_POR_CLIENTE" Method="SP_OBTENER_PAYMENT_LINKS_POR_CLIENTE">
    <Parameter Name="OnvoCustomerId" Parameter="onvoCustomerId" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SP_OBTENER_PAYMENT_LINKS_POR_CLIENTEResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OnvoCustomerId" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OnvoPaymentLinkId" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ReferenceId" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentUrl" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ExpiresAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaActualizacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StatusDescripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_CALIFICAR_PROFESIONAL" Method="SP_CALIFICAR_PROFESIONAL">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdCita" Parameter="idCita" Type="System.Int32" DbType="Int" />
    <Parameter Name="Calificacion" Parameter="calificacion" Type="System.Decimal" DbType="Decimal(3,2)" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_OBTENER_CALIFICACION_PROMEDIO_PROFESIONAL" Method="SP_OBTENER_CALIFICACION_PROMEDIO_PROFESIONAL">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdPerfilProfesional" Parameter="idPerfilProfesional" Type="System.Int32" DbType="Int" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="SP_OBTENER_CALIFICACION_PROMEDIO_PROFESIONALResult">
      <Column Name="CalificacionPromedio" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_AGREGAR_HORARIO_PROFESIONAL" Method="SP_AGREGAR_HORARIO_PROFESIONAL">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="HoraInicio" Parameter="horaInicio" Type="System.TimeSpan" DbType="Time" />
    <Parameter Name="HoraFin" Parameter="horaFin" Type="System.TimeSpan" DbType="Time" />
    <Parameter Name="FechaDiaSemana" Parameter="fechaDiaSemana" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Estado" Parameter="estado" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CREAR_EVENTO_PROFESIONAL" Method="SP_CREAR_EVENTO_PROFESIONAL">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="NombreEvento" Parameter="nombreEvento" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="FechaHoraInicio" Parameter="fechaHoraInicio" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FechaHoraFin" Parameter="fechaHoraFin" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IdEventoCreado" Parameter="idEventoCreado" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="HorariosAfectados" Parameter="horariosAfectados" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_LISTAR_CITAS_CLIENTE" Method="SP_LISTAR_CITAS_CLIENTE">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="SP_LISTAR_CITAS_CLIENTEResult">
      <Column Name="IdCita" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaCita" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DuracionMinutos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrecioAcordado" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MensajeSolicitud" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MotivoRechazo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MotivoCancelacion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FechaSolicitud" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaRespuesta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CedulaUsuario" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NombreUsuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EmailUsuario" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TelefonoUsuario" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IdProfesional" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreProfesional" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Profesion" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EstadoCalificacion" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="CalificacionPromedio" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="DescripcionPerfil" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="EmailProfesional" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TelefonoProfesional" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NombreServicio" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_LISTAR_CITAS_PROFESIONAL" Method="SP_LISTAR_CITAS_PROFESIONAL">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="SP_LISTAR_CITAS_PROFESIONALResult">
      <Column Name="IdCita" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaCita" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DuracionMinutos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrecioAcordado" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MensajeSolicitud" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MotivoRechazo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MotivoCancelacion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FechaSolicitud" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaRespuesta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CedulaUsuario" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NombreUsuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EmailUsuario" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TelefonoUsuario" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IdProfesional" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreProfesional" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Profesion" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EstadoCalificacion" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="CalificacionPromedio" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="DescripcionPerfil" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="EmailProfesional" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TelefonoProfesional" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NombreServicio" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_LISTAR_SERVICIOS_PROFESIONAL" Method="SP_LISTAR_SERVICIOS_PROFESIONAL">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="NombreServicio" Parameter="nombreServicio" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="SUCCESS" Parameter="sUCCESS" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="SP_LISTAR_SERVICIOS_PROFESIONALResult">
      <Column Name="IdServicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdPerfil" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DuracionMinutos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="PermiteDescuento" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PorcentajeDescuento" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>